schema-version: v1
kind: workflow
metadata:
  name: wkflw-git-alien-languages
  display-name: wkflw-git-alien-languages
  description: Teste documentação inválida
  version: 0.0.1
spec:
  type: reusable
  label: Título do Workflow
  docs:
    fr-zp: docs/fr_zp/docs.md
    jh-ex: docs/jr_ex/docs.md
    
  jobs:
    - id: job_id_1
      label: Job que diz olá
      steps:
        - id: step_id_1
          label: Passo que diz olá
          type: run
          script: |
            echo "Olá Mundo"

#    - id: exemplo_1
#      label: Exemplos de passos
#      steps:
#        - id: exemplo_1
#          label: Exemplo de passo que executa uma ação
#          name: stackspot/hello-world@1.0.0
#          type: action
#          inputs:
#            input_1: "Este é um exemplo de input fixo"
#
#        - id: exemplo_2
#          label: Exemplo de passo que aplica um plugin
#          name: stackspot/plugin-basic@1.0.0
#          type: plugin
#          inputs:
#            input_1: "Este é um exemplo de input fixo"
#
#        - id: exemplo_3
#          label: Exemplo de passo suspenso
#          type: suspend
#
#    - id: exemplo_2
#      label: Exemplo de passo workflow
#      depends-on:
#        - job_id_1
#      steps:
#        - id: step_id_1
#          name: stackspot/workflow@1.0.0
#          type: workflow
#          inputs:
#            input_1: "Este é um exemplo de input fixo"
